### ISSUE TITLE
Frontend Language

### ISSUE THREAD

**Issue by dalliard** [nextsport/app#17]
Which front end language will be used to realize the application?

HTML and CSS for sure.

But which framework, if any framework.

Bootstrap?

**Comment by zeromalist** [comment]
In project 2 I came to the conclusion to use mdbootstrap. But I would prefer to use googles material components. The reason for the change is mainly, that I don't want to be dependent on a payed material design implementation.

Will mention this change in the next meeting with the supervisor.

**Comment by dalliard** [comment]
Got an okay from supervisor. Still need to ask stake client.

**Comment by dalliard** [comment]
Got an okay from the client.
